spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false
  r2dbc:
    #url: r2dbc:postgresql://localhost/app-bingo
 # username: postgres
  #password: postgres

    url: r2dbc:postgresql://ec2-54-208-11-146.compute-1.amazonaws.com/d2ggqgof9kor64
    username: igisqmwurbycdk
    password: 392ea4e44118671c66917b6174814fef046c7b17e1877527d3df7e71cd3f0f8a

  application:
    name: betbillions
  data:
    mongodb:
      uri: "mongodb+srv://dbuser:DMekHRirbSkdNyfj@cluster0.s4e6i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
jwt:
  secret: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A
  expiration: 3600
bet_billions:
  url: https://betbillions.com.co/
  email:
    sender: corporate@betbillions.com.co
    password : Fara4020**
