spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false
  r2dbc:
    url: r2dbc:postgresql://3.140.1.248:5432/bd-prueba
    username: postgres
    password: evoxproduccion
  application:
    name: betbillions
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
  expiration: 3600
bet_billions:
  url: https://betbillions.com.co/
  email:
    sender: corporate@betbillions.com.co
    password : Fara4020**
