spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false
  r2dbc:
    url: r2dbc:postgresql://167.86.126.237/betbillions
    username: postgres
    password: Lider123**
  application:
    name: betbillions
  data:
    mongodb:
      uri: "mongodb+srv://dbuser:DMekHRirbSkdNyfj@cluster0.s4e6i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
  expiration: 3600
bet_billions:
  url: https://betbillions.com.co/
  email:
    sender: corporate@betbillions.com.co
    password : Fara4020**
